# yamllint configuration for Podgrab
# Documentation: https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Trailing spaces
  trailing-spaces: enable

  # Document start (---)
  document-start:
    present: false  # Not required for all YAML files

  # Comments
  comments:
    min-spaces-from-content: 1

  # Empty lines
  empty-lines:
    max: 2

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false  # Don't check keys, only values

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Comments indentation
  comments-indentation: enable

  # Empty values
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true

  # Key duplicates
  key-duplicates: enable

  # New line at end of file
  new-line-at-end-of-file: enable

ignore: |
  /vendor/
  /.git/
  /node_modules/
  /webassets/
  /client/
